apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: racher.io/local-path # Потрібен встановлений провізіонер
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete # Диск видалиться автоматично після видалення PVC
