apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stage01
  namespace: flux-system
spec:
  interval: 1m
  path: ./rendered
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-stage01
  targetNamespace: stage-01

