apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-service
spec:
  values:
    image:
      tag: "ghcr.io/skiyl9x/backend-api-service:main-20260219-212441-33d187c" # {"$imagepolicy": "flux-system:backend-api-service-policy-dev-01:tag"}
    replicaCount: 4
