apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: api-service
spec:
  values:
    image:
      tag: "main-92c585e" # {"$imagepolicy": "flux-system:backend-api-service-policy-dev-01"}
    replicaCount: 4
