apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-01
  namespace: flux-system
spec:
  interval: 1m
  path: ./rendered
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-dev-01
  targetNamespace: dev-01

