apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 39.0.0
  install:
    createNamespace: true
  interval: 1h0m0s
  releaseName: traefik
  storageNamespace: traefik-system
  targetNamespace: traefik-system
  values:
    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
        - web
        matchRule: Host(`dashboard.localhost`)
    ports:
      traefik:
        exposedPort: 8080
        port: 8080
      web:
        exposedPort: 80
        port: 8000
      websecure:
        exposedPort: 443
        port: 8443
    providers:
      kubernetesGateway:
        enabled: true
