apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- gitrepositories/rendered-dev.yaml
- gitrepositories/rendered-stage.yaml
- helmrepositories/bitnami.yaml
- ../apps-dev-01.yaml
- ../apps-stage-01.yaml
- ../infrastructure.yaml 
