apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  releaseName: traefik
  targetNamespace: traefik-system
  storageNamespace: traefik-system
  install:
    createNamespace: true
  interval: 1h0m0s
  chart:
    spec:
      chart: traefik
      version: "39.0.0" # Adjust based on current latest version
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    # Optional: Enable the Traefik Dashboard
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`dashboard.localhost`)
        entryPoints:
          - web
    # Enable the modern Gateway API provider
    providers:
      kubernetesGateway:
        enabled: true
#    gateway:
#      listeners:
#        web:
#          namespacePolicy:
#            from: All
    ports:
      web:
        port: 8000        # Matches --entryPoints.web.address
        exposedPort: 80   # What you'll use in your browser (http://<IP>)
      websecure:
        port: 8443        # Matches --entryPoints.websecure.address
        exposedPort: 443  # What you'll use in your browser (https://<IP>)
      traefik:
        port: 8080        # Matches --entryPoints.traefik.address
        exposedPort: 8080 # Usually kept the same for the dashboard

    # #Expose the dashboard on a specific port if needed
    # ports:
    #   traefik:
    #     expose:
    #      default: true
