apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-01
  namespace: flux-system
spec:
  interval: 1m
  path: ./rendered
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-prod-01
  targetNamespace: prod-01

