name: Render Manifests

on:
  push:
    branches: [main]
    paths:
      - 'apps/**'

permissions:
  contents: write
  pull-requests: write
jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_branch: [dev-01, stage-01, prod-01]
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          path: main

      - name: Install Kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/

      - name: Render Manifests
        working-directory: main
        run: |
          set -x
          for app_dir in apps/overlays/${{ matrix.target_branch }}/*; do
            app_name=$(basename ${app_dir})
            mkdir -p ../tmp/rendered
            kustomize build apps/overlays/${{ matrix.target_branch }}/${app_name} > ../tmp/rendered/${app_name}.yaml
          done

      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ matrix.target_branch }}
          path: ${{ matrix.target_branch }}

      - name: Push Manifests
        if: ${{ matrix.target_branch != 'stage-01' && matrix.target_branch != 'prod-01' }}
        working-directory: ${{ matrix.target_branch }}
        run: |
          set -x
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          mkdir -p rendered/
          cp -rf ../tmp/rendered/* rendered/
          git add rendered
          git commit -m "Update rendered manifests with run id ${{ github.run_id }}" || echo "No changes"
          git push origin ${{ matrix.target_branch }}

      - name: Commit and Push to Rendered Branch
        id: commit_and_push
        if: ${{ matrix.target_branch == 'stage-01' || matrix.target_branch == 'prod-01' }}
        working-directory: ${{ matrix.target_branch }}
        run: |
          set -x
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b rendered--${{ matrix.target_branch }}--${{ github.run_id }}
          mkdir -p rendered
          cp -rf ../tmp/rendered/* rendered/
          git add .
          if git commit -m "Update rendered manifests for ${{ matrix.target_branch }}"; then
            git push --set-upstream origin rendered--${{ matrix.target_branch }}--${{ github.run_id }}
            printf "result=done\n" >> "${GITHUB_OUTPUT}"
          else
            printf "result=skipped\n" >> "${GITHUB_OUTPUT}"
          fi

      - name: Create PR
        if: ${{ (matrix.target_branch == 'stage-01' || matrix.target_branch == 'prod-01') && steps.commit_and_push.outputs.result == 'done' }}
        working-directory: ${{ matrix.target_branch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          # Get numbers of old pull requests
          PR_NUMS_OLD=$(gh pr list --base ${{ matrix.target_branch }} --state open --json number -q '.[].number')
          # Create new pull request and save the url
          PR_URL=$(gh pr create --base ${{ matrix.target_branch }} -t "${{ matrix.target_branch }}: new updates with id ${{ github.run_id }}" --body "")
          # Delete old pull requests and branches
          if [ -n "${PR_NUMS_OLD}" ]; then
            echo "${PR_NUMS_OLD}" | xargs -n1 gh pr close --delete-branch --comment "New PR is created: ${PR_URL}"
          fi
